### PR TITLE
ci: add github action for terraform validate

### PR DESCRIPTION
**Pull request by marekaf**

### CODE REVIEW

**Review by jendakol — COMMENTED** [review]
Could you add `deploy.yaml` validation too?

**Comment by marekaf** [comment]
> Could you add `deploy.yaml` validation too?

I'm not sure there are any validators for Cloud Build. I can only validate the yaml.

**Comment by jendakol** [comment]
That's what I meant - a simple yaml validation.

**Comment by jendakol** [comment]
@marekaf Looks like the linter is linting itself :-) It seems it works :-D

**Comment by marekaf** [comment]
done, check pls @jendakol

**Review by jendakol — APPROVED** [review]

**Pull request merged**
