### PR TITLE
SendWakeUpSignal: disable authentication; run sendwakeupsignal worker

### PR DESCRIPTION
**Pull request by jendakol**
cc @davidvavra

### CODE REVIEW

**Comment by davidvavra** [comment]
@jendakol Why every 4 hours? Once a day is enough.

**Comment by jendakol** [comment]
@davidvavra We've shorten the export file generation period to 6 hours so I thought it will be fine if we can provide results to our users ASAP. But I can prolong it, if you think.

**Comment by davidvavra** [comment]
@jendakol I'm worried about increased battery consumption. Do I understand it correctly that eRouška only analyzes data from previous days, not from the current day? So analyzing multiple times a day doesn't bring any value to the user?

**Comment by marekaf** [comment]
pls rebase

**Comment by jendakol** [comment]
Rebased and edited (every day, 9 am).

**Review by marekaf — APPROVED** [review]
lgtm

**Pull request merged**
