### PR TITLE
feat: CDN for key server

### PR DESCRIPTION
**Pull request by marekaf**

### CODE REVIEW

**Review by vranystepan — APPROVED** [review]
smooth.

**Comment by marekaf** [comment]
> smooth.

but is it like silky smooth or more like smooth-ish?

**Comment by vranystepan** [comment]
> > smooth.
> 
> but is it like silky smooth or more like smooth-ish?

silky smooth <3

**Comment by marekaf** [comment]
> > > smooth.
> > 
> > 
> > but is it like silky smooth or more like smooth-ish?
> 
> silky smooth <3

ahaa! I was gonna rage-merge anywayyy!

**Pull request merged**
