### PR TITLE
Silent pushes

### LINKED ISSUE #133: Send silent push to trigger key download every day
Some devices are not downloading keys due to system killing the scheduled tasks. Silent push should help with that.

Once a day, send following push notification to all registered eHrids with push tokens:

Custom payload:
Key: `downloadKeyExport`
Value: true

Priority: `high`

Expiration: 1 day

Make sure to delete all invalid push tokens from database (follow response from Google server).

Will this also work with users who upgraded from v1 and have only FUID, not eHrid?

### PR DESCRIPTION
**Pull request by jendakol**
SendWakeUpSignal function sends a high-priority push message to devices which should wake the app if it was sleeping.  
cc @davidvavra

### CODE REVIEW

**Review by marekaf — APPROVED** [review]
lgtm

**Comment by jendakol** [comment]
Closes #133

**Comment by jendakol** [comment]
@davidvavra This should run every 4 hours. Please check.

**Comment by davidvavra** [comment]
@jendakol I would rather send it few times only manually and observe the data. Only if we see significant improvement, enable schedule.

**Pull request merged**
